<a href="https://colab.research.google.com/github/SaiAnjesh/Learning-Pytorch/blob/main/Tutorials/Tutorial_D2L_Pytorch_Chapter_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# Tensors Introduction
var1 = torch.arange(12, dtype=torch.float32)
print(var1.numel())
var1

12


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
var2 = var1.reshape(3, 4)
var2

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [4]:
# Tensors - Ones / Zeros / Rand
print(torch.zeros((2, 3, 4)))
print(torch.ones((2, 3, 4)))
print(torch.randn(3, 4))
print((torch.tensor([[2, 3, 1,], [4, 3, 5, ], [5, 6, 7,]])))
print(type(torch.tensor([[2, 3, 1,], [4, 3, 5, ], [5, 6, 7,]])))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[-0.7695, -0.8968,  1.0771, -1.5424],
        [ 1.4071,  0.7982,  1.8987,  2.5274],
        [ 0.4718,  2.6298,  0.1891, -0.8905]])
tensor([[2, 3, 1],
        [4, 3, 5],
        [5, 6, 7]])
<class 'torch.Tensor'>


In [5]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [6]:
A = x.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [7]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [19]:
# Automatic Differentiation
x = torch.arange(4.0)
x.requires_grad_(True)
print(x)
x.grad


tensor([0., 1., 2., 3.], requires_grad=True)


In [20]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [21]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [22]:
x.grad == 4 * x

tensor([True, True, True, True])

In [23]:
x.grad.zero_()  # Reset the gradient
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])