<a href="https://colab.research.google.com/github/SaiAnjesh/Learning-Pytorch/blob/main/Tutorials/Tutorial_D2L_Pytorch_Chapter_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# Tensors Introduction
var1 = torch.arange(12, dtype=torch.float32)
print(var1.numel())
var1

12


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
var2 = var1.reshape(3, 4)
var2

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
# Tensors - Ones / Zeros / Rand
print(torch.zeros((2, 3, 4)))
print(torch.ones((2, 3, 4)))
print(torch.randn(3, 4))
print((torch.tensor([[2, 3, 1,], [4, 3, 5, ], [5, 6, 7,]])))
print(type(torch.tensor([[2, 3, 1,], [4, 3, 5, ], [5, 6, 7,]])))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[ 0.3218,  2.2312, -0.0090, -0.7542],
        [-0.8680,  1.4209, -1.7692,  0.5415],
        [-0.0976,  2.0876,  0.4980, -0.8539]])
tensor([[2, 3, 1],
        [4, 3, 5],
        [5, 6, 7]])
<class 'torch.Tensor'>


In [ ]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [ ]:
A = x.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [ ]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)